[package]
name = "oysterpack-smart-near-test"
version = "0.1.0"
authors = ["oysterpack.inc <2zP6OaymGZhJTHFvQMzp6Ze>"]
edition = "2018"

[dependencies]
near-sdk = "=3.0.1-pre.1"
near-vm-logic = "3.0.0"
oysterpack-smart-near = {path = "../oysterpack-smart-near"}